import Link from "next/link";

const sections = [
  ["1", "Qué información tratamos", "Si creás una cuenta, tratamos tu email y los datos que decidas completar en tu perfil. Si guardás un escenario, almacenamos su nombre, los valores ingresados y los resultados para que puedas consultarlos más adelante."],
  ["2", "Cómo usamos la información", "Usamos esos datos para autenticarte, mostrar tu perfil, conservar tus escenarios y conversaciones, controlar los límites del plan gratuito y prestar las funciones de la plataforma. No vendemos tu información personal."],
  ["3", "Cálculos y escenarios", "Podés usar las calculadoras sin guardar un escenario. Cuando elegís guardarlo en tu cuenta, sus datos quedan asociados a tu usuario y podés eliminarlos desde tu perfil."],
  ["4", "Asistente con inteligencia artificial", "Cuando solicitás un análisis o enviás un mensaje al asistente, compartimos con OpenAI los datos de la calculadora, sus resultados y el texto de la conversación necesarios para generar una respuesta. No incluyas contraseñas, datos bancarios ni información personal sensible. Las respuestas son orientativas y no reemplazan asesoramiento profesional."],
  ["5", "Proveedores de servicio", "Utilizamos Supabase para autenticación y almacenamiento de cuentas, escenarios y conversaciones; OpenAI para generar las respuestas del asistente; y Vercel para alojar y publicar la aplicación. Cada proveedor procesa información para prestar su servicio y aplica sus propias medidas y condiciones de seguridad."],
  ["6", "Cookies y tecnologías similares", "Usamos almacenamiento local o cookies necesarias para mantener tu sesión, completar el ingreso y recordar información temporal del servicio. Si incorporamos herramientas de medición o publicidad, actualizaremos esta política antes de utilizarlas."],
  ["7", "Tus opciones", "Podés editar los datos de tu perfil, eliminar escenarios y conversaciones guardadas, y cerrar sesión en cualquier momento. Para solicitar acceso, corrección o eliminación completa de tu cuenta y sus datos, escribinos por email."],
  ["8", "Seguridad y conservación", "Aplicamos medidas razonables para proteger la información y controles para que cada usuario acceda solamente a sus propios datos. Conservamos la información mientras tu cuenta esté activa o mientras sea necesaria para ofrecer el servicio y cumplir obligaciones aplicables."],
  ["9", "Cambios en esta política", "Podemos actualizar esta política cuando cambien las funciones, proveedores o prácticas de la plataforma. La versión vigente y su fecha de actualización siempre estarán publicadas en esta página."],
];

export default function PoliticaPage() {
  return <main className="min-h-screen bg-zinc-950 text-white">
    <section className="border-b border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(52,211,153,0.12),transparent_42%)]"><div className="mx-auto max-w-5xl px-6 py-16 sm:py-20"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-300/75">Transparencia y confianza</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Política de privacidad</h1><p className="mt-5 max-w-2xl leading-7 text-white/60">Te contamos de forma clara qué información usamos, por qué la necesitamos y qué opciones tenés sobre tus datos.</p><p className="mt-5 text-xs text-white/35">Última actualización: 15 de julio de 2026</p></div></section>
    <div className="mx-auto max-w-5xl px-6 py-14"><div className="grid gap-5">{sections.map(([number,title,text]) => <section key={number} className="grid gap-4 rounded-2xl border border-white/10 bg-white/[0.03] p-6 sm:grid-cols-[3rem_1fr]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-300/10 text-sm font-bold text-emerald-300">{number}</span><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-white/55">{text}</p></div></section>)}</div>
      <section className="mt-10 rounded-3xl border border-emerald-300/20 bg-emerald-300/[0.05] p-7"><p className="text-sm font-semibold text-emerald-300">¿Tenés una consulta sobre tus datos?</p><p className="mt-3 text-white/60">Escribinos a <a className="font-medium text-white hover:text-emerald-300" href="mailto:calculadoraemprendedora@gmail.com">calculadoraemprendedora@gmail.com</a>.</p><Link href="/contacto" className="mt-5 inline-block text-sm font-semibold text-emerald-300">Ir a contacto →</Link></section>
    </div>
  </main>;
}
