create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_kind text not null check (usage_kind in ('analysis', 'chat')),
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_events_user_kind_created_idx
  on public.ai_usage_events (user_id, usage_kind, created_at desc);

alter table public.ai_usage_events enable row level security;

-- Usage can only be registered through consume_ai_quota(). Keeping the table
-- private prevents users from deleting events to reset their own allowance.
revoke all on public.ai_usage_events from anon, authenticated;

create or replace function public.consume_ai_quota(p_kind text)
returns table (
  allowed boolean,
  used integer,
  quota_limit integer,
  resets_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_now_local timestamp := pg_catalog.now() at time zone 'America/Argentina/Buenos_Aires';
  v_period_start_local timestamp;
  v_period_end_local timestamp;
  v_period_start timestamptz;
  v_period_end timestamptz;
  v_limit integer;
  v_used integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_kind = 'analysis' then
    v_limit := 1;
    v_period_start_local := pg_catalog.date_trunc('week', v_now_local);
    v_period_end_local := v_period_start_local + interval '1 week';
  elsif p_kind = 'chat' then
    v_limit := 10;
    v_period_start_local := pg_catalog.date_trunc('day', v_now_local);
    v_period_end_local := v_period_start_local + interval '1 day';
  else
    raise exception 'Invalid usage kind';
  end if;

  v_period_start := v_period_start_local at time zone 'America/Argentina/Buenos_Aires';
  v_period_end := v_period_end_local at time zone 'America/Argentina/Buenos_Aires';

  -- Serializes simultaneous requests from the same user and quota type.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_user_id::text || ':' || p_kind, 0)
  );

  select pg_catalog.count(*)::integer
    into v_used
    from public.ai_usage_events
   where user_id = v_user_id
     and usage_kind = p_kind
     and created_at >= v_period_start
     and created_at < v_period_end;

  if v_used >= v_limit then
    return query select false, v_used, v_limit, v_period_end;
    return;
  end if;

  insert into public.ai_usage_events (user_id, usage_kind)
  values (v_user_id, p_kind);

  return query select true, v_used + 1, v_limit, v_period_end;
end;
$$;

revoke all on function public.consume_ai_quota(text) from public, anon;
grant execute on function public.consume_ai_quota(text) to authenticated;
