-- Telemetria privada de OpenAI y proteccion distribuida contra rafagas.
-- Los usuarios nunca acceden directamente a estos registros.

create table if not exists public.ai_provider_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_event_id bigint references public.ai_usage_events(id) on delete set null,
  request_id uuid not null,
  provider text not null default 'openai' check (provider = 'openai'),
  mode text not null check (mode in ('analysis', 'chat')),
  plan text not null check (plan in ('free', 'pro')),
  requested_model text not null,
  provider_model text,
  status text not null default 'started' check (status in ('started', 'succeeded', 'failed', 'cancelled')),
  provider_request_id text,
  provider_response_id text,
  input_tokens bigint check (input_tokens is null or input_tokens >= 0),
  cached_input_tokens bigint check (
    cached_input_tokens is null
    or (input_tokens is not null and cached_input_tokens >= 0 and cached_input_tokens <= input_tokens)
  ),
  output_tokens bigint check (output_tokens is null or output_tokens >= 0),
  total_tokens bigint check (total_tokens is null or total_tokens >= 0),
  estimated_cost_usd numeric(14, 8) check (estimated_cost_usd is null or estimated_cost_usd >= 0),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  provider_status integer check (provider_status is null or provider_status between 100 and 599),
  error_code text,
  created_at timestamptz not null default pg_catalog.now(),
  completed_at timestamptz
);

create index if not exists ai_provider_events_user_created_idx
  on public.ai_provider_events (user_id, created_at desc);

create index if not exists ai_provider_events_usage_event_idx
  on public.ai_provider_events (usage_event_id)
  where usage_event_id is not null;

create index if not exists ai_provider_events_request_idx
  on public.ai_provider_events (request_id);

create index if not exists ai_messages_user_id_idx
  on public.ai_messages (user_id);

alter table public.ai_provider_events enable row level security;

-- Defensa en profundidad: aunque public sea un schema expuesto, esta tabla solo
-- queda disponible para la clave privada usada por el servidor.
revoke all on table public.ai_provider_events from public, anon, authenticated;
revoke all on sequence public.ai_provider_events_id_seq from public, anon, authenticated;
grant select, insert, update on table public.ai_provider_events to service_role;
grant usage, select on sequence public.ai_provider_events_id_seq to service_role;

-- Mantiene privados tambien los eventos que funcionan como reservas de cuota.
revoke all on table public.ai_usage_events from public, anon, authenticated;

drop function if exists public.consume_ai_quota(text);

create function public.consume_ai_quota(p_kind text)
returns table (
  allowed boolean,
  used integer,
  quota_limit integer,
  resets_at timestamptz,
  plan text,
  usage_event_id bigint,
  denial_reason text,
  burst_limit integer,
  burst_retry_after_seconds integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_plan text := 'free';
  v_now timestamptz := pg_catalog.now();
  v_now_local timestamp := v_now at time zone 'America/Argentina/Buenos_Aires';
  v_period_start_local timestamp;
  v_period_end_local timestamp;
  v_period_start timestamptz;
  v_period_end timestamptz;
  v_limit integer;
  v_used integer;
  v_usage_event_id bigint;
  v_burst_limit integer;
  v_burst_used integer;
  v_burst_oldest_at timestamptz;
  v_burst_retry_after_seconds integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_kind is null or p_kind not in ('analysis', 'chat') then
    raise exception 'Invalid usage kind';
  end if;

  if public.has_pro_access(v_user_id) then
    v_plan := 'pro';
  end if;

  if v_plan = 'pro' then
    v_limit := case p_kind when 'analysis' then 30 else 300 end;
    v_burst_limit := 10;
    v_period_start_local := pg_catalog.date_trunc('month', v_now_local);
    v_period_end_local := v_period_start_local + interval '1 month';
  elsif p_kind = 'analysis' then
    v_limit := 1;
    v_burst_limit := 3;
    v_period_start_local := pg_catalog.date_trunc('week', v_now_local);
    v_period_end_local := v_period_start_local + interval '1 week';
  else
    v_limit := 5;
    v_burst_limit := 3;
    v_period_start_local := pg_catalog.date_trunc('day', v_now_local);
    v_period_end_local := v_period_start_local + interval '1 day';
  end if;

  v_period_start := v_period_start_local at time zone 'America/Argentina/Buenos_Aires';
  v_period_end := v_period_end_local at time zone 'America/Argentina/Buenos_Aires';

  -- Una unica traba por usuario serializa analysis y chat en todas las
  -- instancias, por lo que el limite corto no depende de memoria local.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_user_id::text || ':ai-quota', 0)
  );

  select pg_catalog.count(*)::integer
    into v_used
    from public.ai_usage_events event
   where event.user_id = v_user_id
     and event.usage_kind = p_kind
     and event.created_at >= v_period_start
     and event.created_at < v_period_end;

  if v_used >= v_limit then
    return query select
      false,
      v_used,
      v_limit,
      v_period_end,
      v_plan,
      null::bigint,
      'quota'::text,
      v_burst_limit,
      null::integer;
    return;
  end if;

  select pg_catalog.count(*)::integer, pg_catalog.min(event.created_at)
    into v_burst_used, v_burst_oldest_at
    from public.ai_usage_events event
   where event.user_id = v_user_id
     and event.usage_kind in ('analysis', 'chat')
     and event.created_at > v_now - interval '60 seconds';

  if v_burst_used >= v_burst_limit then
    v_burst_retry_after_seconds := pg_catalog.ceil(
      extract(epoch from (v_burst_oldest_at + interval '60 seconds' - v_now))
    )::integer;
    if v_burst_retry_after_seconds < 1 then
      v_burst_retry_after_seconds := 1;
    end if;

    return query select
      false,
      v_used,
      v_limit,
      v_period_end,
      v_plan,
      null::bigint,
      'burst'::text,
      v_burst_limit,
      v_burst_retry_after_seconds;
    return;
  end if;

  insert into public.ai_usage_events (user_id, usage_kind)
  values (v_user_id, p_kind)
  returning id into v_usage_event_id;

  return query select
    true,
    v_used + 1,
    v_limit,
    v_period_end,
    v_plan,
    v_usage_event_id,
    null::text,
    v_burst_limit,
    null::integer;
end;
$$;

revoke all on function public.consume_ai_quota(text) from public, anon, authenticated;
grant execute on function public.consume_ai_quota(text) to authenticated;
